---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: keyvault-flexvolume
  name: keyvault-flexvolume
  namespace: kv
spec:
  template:
    metadata:
      labels:
        app: keyvault-flexvolume
    spec:
      containers:
      - env:
        - name: TARGET_DIR
          value: /etc/kubernetes/volumeplugins
        image: mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume:v0.0.15
        imagePullPolicy: Always
        name: flexvol-driver-installer
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/volumeplugins
          name: volplugins
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
      - hostPath:
          path: /etc/kubernetes/volumeplugins
        name: volplugins
  updateStrategy:
    type: RollingUpdate

