---	
apiVersion: v1	
kind: ServiceAccount	
metadata:	
  name: geneva	
  namespace: default	

---	
apiVersion: rbac.authorization.k8s.io/v1beta1	
kind: ClusterRoleBinding	
metadata:	
  name: geneva	
  namespace: default	
roleRef:	
  apiGroup: rbac.authorization.k8s.io	
  kind: ClusterRole	
  name: cluster-admin	
subjects:	
- kind: ServiceAccount	
  name: geneva	
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: geneva-azsecpack
  name: geneva-azsecpack
  namespace: default
spec:
  selector:
    matchLabels:
      name: geneva-azsecpack
  template:
    metadata:
      labels:
        name: geneva-azsecpack
    spec:
      containers:
      - env:
        - name: AzSecPack_GCS_cert
          value: /secrets/gcscert.pem
        - name: AzSecPack_GCS_key
          value: /secrets/gcskey.pem
        - name: AzSecPack_GCS_Environment
          value: DiagnosticsProd
        - name: AzSecPack_GCS_Account
          value: smartdctest
        - name: AzSecPack_EventVersion
          value: "3"
        - name: AzSecPack_Timestamp
          value: 2020-04-29T00:00:00Z
        - name: AzSecPack_Namespace
          value: CihAtlasK8sTest
        - name: AzSecPack_Moniker
          value: cihatlask8stestsecurity
        - name: AzSecPack_Tenant
          value: atlasdataquality
        - name: AzSecPack_Role
          value: atlas-dq-dev
        - name: AzSecPack_RoleInstance
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AzSecPack_MachineName
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: AzSecPack_MonitorForFailure
          value: "1"
        image: xddevacr.azurecr.io/genevasecpackinstall:master_53
        imagePullPolicy: IfNotPresent
        name: azsecpack
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 75Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host
          name: azsecpack-host
        - mountPath: /secrets
          name: azsecpack-auth-vol
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: geneva
      serviceAccountName: geneva
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
          type: ""
        name: azsecpack-host
      - name: azsecpack-auth-vol
        secret:
          defaultMode: 420
          secretName: geneva-certificate
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate